# port
server:
  port: 8888
  servlet:
    context-path: /
    session:
      persistent: true
# db
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/webtraodoisp
    username: root
    password: manh1422000
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# uploading
data:
  path: F:/dev/source/res/

session:
  login: USER_LOGIN
